// Generate tests/knockback-fixture.json from web/src/engine/knockback.js.
//
//     node tests/genfixture.mjs
//
// check.sh runs this on EVERY run, and that is the point. The fixture used to be a committed
// snapshot regenerated by hand from a command buried in the README, which meant the parity test
// could only catch drift someone had already noticed: the day the JS launch curve changed, the
// Luau port silently stopped matching it and `./check.sh` still printed "matches exactly".
// Regenerating first makes the check compare the port against the CURRENT JavaScript.
import * as K from '../../web/src/engine/knockback.js';
import fs from 'node:fs';

const BASES = [8, 12, 16, 20, 26, 30, 32, 34];
const GROWTHS = [0, 0.8, 1.6, 2.4, 3.2, 4.4, 5.2, 5.7];
const DAMAGES = [1, 3, 5, 8, 12, 15, 17];
const PERCENTS = [0, 37, 80, 113, 150, 199, 300];
const WEIGHTS = [90, 96, 100, 108];
const r9 = (n) => +n.toFixed(9);

// launch and stun are two different curves now (KNOCKBACK.slope vs stunSlope), so both are
// sampled - and hitstun is taken from the STUN speed, which is how combat.js feeds it.
const launch = [];
for (const base of BASES) for (const growth of GROWTHS) for (const damage of DAMAGES)
  for (const pct of PERCENTS) for (const weight of WEIGHTS) {
    const L = K.launchSpeed(base, growth, damage, pct, weight);
    const S = K.stunSpeed(base, growth, damage, pct, weight);
    launch.push([base, growth, damage, pct, weight, r9(L), K.hitstun(S), r9(S)]);
  }

const velocity = [];
for (const l of [8, 20, 33.5, 45, 60, 88]) for (const a of [20, 40, 55, 70, 88, 275])
  for (const f of [1, -1])
    for (const di of [null, { x: 0, y: 1 }, { x: 0, y: -1 }, { x: 1, y: 0 }, { x: -1, y: 0 }, { x: 0.5, y: -0.5 }]) {
      const v = K.velocity(l, a, f, di);
      velocity.push([l, a, f, di ? di.x : 0, di ? di.y : 0, di ? 1 : 0, r9(v.vx), r9(v.vy)]);
    }

const misc = [];
for (const d of [0, 1, 2, 3, 5, 8, 12, 15, 17, 20, 30]) misc.push([d, K.blockstun(d), K.hitlag(d, false), K.hitlag(d, true)]);

const out = new URL('./knockback-fixture.json', import.meta.url);
fs.writeFileSync(out, JSON.stringify({ launch, velocity, misc }));
console.log(`fixture regenerated: ${launch.length} launch rows, ${velocity.length} velocity rows, ${misc.length} misc rows`);
